# Obtener lista de los usuarios que son comisionistas

GET http://localhost:3000/api/advisor/certified

[
  {
    "identity_document": "100038954",
    "first_name": "Santiago",
    "last_name": "Cifuentes",
    "phone": "+573214565462"
  }
]