# Endpoint para obtener el comisionista actual del usuario

GET http://localhost:3000/api/advisor/my-advisor

Authorization: Bearer <token_de_usuario>

{
  "identity_document": "100038954",
  "first_name": "Santiago",
  "last_name": "Cifuentes",
  "phone": "+573214565462"
}